### ISSUE TITLE
Frontend: missing theme files?

### ISSUE THREAD

**Issue by sdevalk** [netwerk-digitaal-erfgoed/omeka-s#1]
I'm configuring Omeka's public-facing frontend using their default theme.

However, the theme is not displayed correctly. For example, a detail page looks like this:

https://omeka.netwerkdigitaalerfgoed.nl/s/schilderijen/item/1

My developer console shows some 404 errors. My guess is that the theme's files aren't installed or unreachable?

<img width="754" alt="console" src="https://user-images.githubusercontent.com/606948/124558552-0730af80-de3b-11eb-9525-e219d73e1005.png">

**Comment by ddeboer** [comment]
Fixed in f01c8613c18f5138f023cbffdb2c5cf55ee70ce5.
